interface OpenApiOperation {
  operationId?: string
}

interface OpenApiDocument {
  paths?: Record<string, Record<string, OpenApiOperation>>
}

const HTTP_METHODS = new Set([
  'delete',
  'get',
  'head',
  'options',
  'patch',
  'post',
  'put',
  'trace',
])

const schema = (await Bun.file(
  new URL('../openapi/openapi.json', import.meta.url),
).json()) as OpenApiDocument

const operationIds = Object.values(schema.paths ?? {})
  .flatMap((path) =>
    Object.entries(path)
      .filter(([method]) => HTTP_METHODS.has(method))
      .map(([, operation]) => operation.operationId),
  )
  .filter((operationId): operationId is string => Boolean(operationId))
  .sort()

const camelCase = (value: string): string =>
  value
    .replace(/[-_]+([a-zA-Z0-9])/g, (_, character: string) =>
      character.toUpperCase(),
    )
    .replace(/^[A-Z]/, (character) => character.toLowerCase())

const pascalCase = (value: string): string => {
  const camel = camelCase(value)
  return camel.length ? `${camel[0]?.toUpperCase()}${camel.slice(1)}` : camel
}

const valueExports = operationIds
  .map((operationId) => {
    const operationName = camelCase(operationId)
    return `  handle${pascalCase(operationId)} as ${operationName}Mock,`
  })
  .join('\n')

const typeExports = operationIds
  .map(
    (operationId) =>
      `  Handle${pascalCase(operationId)}Response as ${pascalCase(operationId)}MockResponse,`,
  )
  .join('\n')

const output = `// Generated by scripts/generate-msw-entry.ts. Do not edit.\n\nexport {\n  createMswHandlers as createOoreMswHandlers,\n${valueExports}\n} from './generated/msw.gen.js'\n\nexport type {\n  CreateMswHandlersResult as CreateOoreMswHandlersResult,\n  RequestHandlerOptions as OoreMswHandlerOptions,\n${typeExports}\n} from './generated/msw.gen.js'\n`

await Bun.write(new URL('../src/msw.ts', import.meta.url), output)
