interface AdapterEntry {
  generatedPath: string
  outputPath: string
}

const entries: ReadonlyArray<AdapterEntry> = [
  {
    generatedPath: '../src/generated/@tanstack/react-query.gen.ts',
    outputPath: '../src/react-query.ts',
  },
]

const collect = (source: string, kind: 'const' | 'type'): Array<string> =>
  Array.from(source.matchAll(new RegExp(`^export ${kind} ([A-Za-z0-9_]+)`, 'gm')))
    .map((match) => match[1])
    .filter((name): name is string => Boolean(name))

const formatNames = (names: ReadonlyArray<string>): string =>
  names.map((name) => `  ${name},`).join('\n')

for (const entry of entries) {
  const generatedUrl = new URL(entry.generatedPath, import.meta.url)
  const source = await Bun.file(generatedUrl).text()
  const valueNames = collect(source, 'const')
  const typeNames = collect(source, 'type')

  if (valueNames.length === 0) {
    throw new Error(`${generatedUrl.pathname} has no exported values`)
  }

  const generatedImport = entry.generatedPath
    .replace('../src/', './')
    .replace(/\.ts$/, '.js')
  const values = `export {\n${formatNames(valueNames)}\n} from '${generatedImport}'\n`
  const types = typeNames.length
    ? `\nexport type {\n${formatNames(typeNames)}\n} from '${generatedImport}'\n`
    : ''
  const output = `// Generated by scripts/generate-adapter-entries.ts. Do not edit.\n\n${values}${types}`

  await Bun.write(new URL(entry.outputPath, import.meta.url), output)
}
