import { mkdir, rm, unlink } from 'node:fs/promises'

import * as ts from 'typescript'

interface SchemaDeclaration {
  initializer: ts.Expression
  name: string
  statement: ts.VariableStatement
}

const generatedUrl = new URL('../src/generated/valibot.gen.ts', import.meta.url)
const source = await Bun.file(generatedUrl).text()
const sourceFile = ts.createSourceFile(
  generatedUrl.pathname,
  source,
  ts.ScriptTarget.Latest,
  true,
  ts.ScriptKind.TS,
)

const schemas: Array<SchemaDeclaration> = []
for (const statement of sourceFile.statements) {
  if (!ts.isVariableStatement(statement)) continue
  if (!statement.getText(sourceFile).startsWith('export const ')) continue

  const declaration = statement.declarationList.declarations[0]
  if (
    statement.declarationList.declarations.length !== 1 ||
    !declaration ||
    !ts.isIdentifier(declaration.name) ||
    !declaration.initializer
  ) {
    throw new Error('Expected each generated Valibot export to declare one value')
  }

  schemas.push({
    initializer: declaration.initializer,
    name: declaration.name.text,
    statement,
  })
}

if (schemas.length === 0) {
  throw new Error('No generated Valibot schemas were found')
}

const schemaNames = new Set(schemas.map(({ name }) => name))
const schemaFiles = new Map(
  schemas.map(({ name }, index) => [
    name,
    `schema-${index.toString().padStart(4, '0')}`,
  ]),
)
const outputDirectory = new URL('../src/generated/valibot/', import.meta.url)
await rm(outputDirectory, { force: true, recursive: true })
await mkdir(outputDirectory, { recursive: true })

await Promise.all(
  schemas.map(async ({ initializer, name, statement }) => {
    const dependencies = new Set<string>()
    const visit = (node: ts.Node): void => {
      if (
        ts.isIdentifier(node) &&
        node.text !== name &&
        schemaNames.has(node.text)
      ) {
        dependencies.add(node.text)
      }
      ts.forEachChild(node, visit)
    }
    visit(initializer)

    const dependencyImport = dependencies.size
      ? `${Array.from(dependencies)
          .sort()
          .map((dependency) => {
            const dependencyFile = schemaFiles.get(dependency)
            if (!dependencyFile) {
              throw new Error(`Missing generated file for ${dependency}`)
            }
            return `import { ${dependency} } from './${dependencyFile}.js'`
          })
          .join('\n')}\n`
      : ''
    const output = `// Generated by scripts/generate-valibot-modules.ts. Do not edit.\n\nimport * as v from 'valibot'\n${dependencyImport}\n${statement.getText(sourceFile)}\n`

    const schemaFile = schemaFiles.get(name)
    if (!schemaFile) throw new Error(`Missing generated file for ${name}`)
    await Bun.write(new URL(`${schemaFile}.ts`, outputDirectory), output)
  }),
)

const publicEntry = `// Generated by scripts/generate-valibot-modules.ts. Do not edit.\n\n${schemas
  .map(({ name }) => {
    const schemaFile = schemaFiles.get(name)
    if (!schemaFile) throw new Error(`Missing generated file for ${name}`)
    return `export { ${name} } from './generated/valibot/${schemaFile}.js'`
  })
  .join('\n')}\n`

await Bun.write(new URL('../src/valibot.ts', import.meta.url), publicEntry)
await unlink(generatedUrl)
